server:
    port: 8100
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            
spring:
    application:
        name: GATEWAY-SERVICE

    
    cloud:
        gateway:
            routes:
                - id: customer-service
                  uri: http://localhost:9094/
                  predicates:
                      - Path=/api/User/**
                - id: admin-service
                  uri: http://localhost:9096/
                  predicates:
                      - Path=/api/admin/**    